version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teacherAvailableTime
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
